version: '3.1'
services:
  app:
    build: .
    ports:
      - "8090:8080"
    networks:
      - s-network
    depends_on:
      - mysql
    command: ["./wait-for-mysql.sh", "mysql", "java -jar your-app.jar"]

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Rahul@123  # Add this line


      MYSQL_DB: student_db
    ports:
      - "3307:3306"
    networks:
      - s-network

networks:
  s-network:
    driver: bridge